version: "1"
rules:
  - base: stable
    upstream: main
    mergeMethod: hardreset
    mergeUnstable: false
    schedule:
      - "0 0 * * MON" # Every Monday at midnight UTC
    reviewers:
      - hanthor
    conflictReviewers:
      - hanthor
label: "promotion"
conflictLabel: "promotion-conflict"
