ARG BASE_IMAGE=ghcr.io/tuna-os/yellowfin:gnome@sha256:2c977e00c9a2a52d3013252310497e367c59c60c2c207c2160ecbcbc2ac1c414
FROM scratch AS ctx
COPY custom /custom
COPY build_scripts /build_scripts

FROM ${BASE_IMAGE}
RUN --mount=type=bind,from=ctx,src=/,target=/run/context \
    /run/context/build_scripts/apply-custom.sh
RUN bootc container lint
