ARG BASE_IMAGE=ghcr.io/tuna-os/yellowfin:gnome@sha256:3a086506b128b0afa5e8a672d554c587381a99b8ed1a27784eaa18945ccaba4b
FROM scratch AS ctx
COPY custom /custom
COPY build_scripts /build_scripts

FROM ${BASE_IMAGE}
RUN --mount=type=bind,from=ctx,src=/,target=/run/context \
    /run/context/build_scripts/apply-custom.sh
RUN bootc container lint
