ARG BASE_IMAGE=ghcr.io/tuna-os/yellowfin:gnome@sha256:18fe5896c0f108b2d02e46f163fb3e89013cc09a85db0a0fba139e4c3a8736fb
FROM scratch AS ctx
COPY custom /custom
COPY build_scripts /build_scripts

FROM ${BASE_IMAGE}
RUN --mount=type=bind,from=ctx,src=/,target=/run/context \
    /run/context/build_scripts/apply-custom.sh
RUN bootc container lint
