[book]
authors = ["TunaOS Team"]
language = "en"
src = "src"
title = "TunaOS Documentation"

[output.html]
git-repository-url = "https://github.com/tuna-os/tunaOS"
edit-endpoint-url = "https://github.com/tuna-os/tunaOS/edit/main/docs/book/src/{path}"
