"""Keep the rolling/experimental availability contract machine-readable.

The distinction is operational, not cosmetic: a red release-track build is a
regression, while a moving upstream can temporarily be incompatible without
violating an uninterrupted-green promise.  Issue #1754 originally carried the
only complete list, which let the policy and matrix drift independently.
"""

from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / ".github" / "build-config.yml"
POLICY = ROOT / "VARIANT-LIFECYCLE.md"
GENERATOR = ROOT / ".github" / "scripts" / "update-build-status.sh"
README = ROOT / "README.md"

NON_RELEASE_TRACKS = {
    "bonito-rawhide": "rolling",
    "flounder-sid": "rolling",
    "guppy": "rolling",
    "hummingbird": "experimental",
    "marlin": "rolling",
    "sailfin": "rolling",
    "wahoo": "experimental",
}


def test_non_release_upstream_tracks_are_explicit_and_complete():
    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    actual = {
        variant["id"]: variant["upstream_track"]
        for variant in config["variants"]
        if "upstream_track" in variant
    }

    assert actual == NON_RELEASE_TRACKS
    assert set(actual.values()) <= {"rolling", "experimental"}


def test_the_readme_matrix_derives_the_release_track_from_the_config():
    """The contract has to reach the artifact people actually read (#1753).

    Being machine-readable is only half of it. `upstream_track` sat in
    build-config.yml with a policy table and this test file pinning it, and no
    generator consuming it -- so the README matrix published one mixed ratio
    in which a rolling upstream's expected churn and a release-track
    regression were the same number, and #1753's recovery target had to be
    reconstructed by hand from a nightly's job logs.

    Pinned as a derivation, not a list: the query, not the seven variants it
    happens to select today.
    """
    body = GENERATOR.read_text(encoding="utf-8")

    assert "upstream_track" in body, (
        "the README matrix generator no longer reads upstream_track; its "
        "release-track subtotal would silently count every variant"
    )
    assert '// "release"' in body, (
        "a variant without upstream_track is on the release/stream track per "
        "VARIANT-LIFECYCLE.md; the generator must default rather than blank"
    )
    assert "Release track:" in body


def test_the_committed_readme_snapshot_carries_the_split():
    """A snapshot regenerated by an older script would drop it silently."""
    block = README.read_text(encoding="utf-8")
    block = block.split("<!-- build-status:start -->")[1].split(
        "<!-- build-status:end -->"
    )[0]

    assert "| Variant | Track |" in block, "the matrix lost its Track column"
    assert "**Release track:" in block
    for track in ("release", "rolling", "experimental"):
        assert f"| {track} |" in block, (
            f"no row is marked {track!r}; either the column stopped being "
            "populated or a whole track left the matrix"
        )


def test_every_non_release_track_has_a_documented_availability_contract():
    policy = POLICY.read_text(encoding="utf-8")

    for variant in NON_RELEASE_TRACKS:
        assert f"`{variant}`" in policy
    assert "no next-night promotion or uninterrupted-green promise" in policy
    assert "No uptime, flavor-completeness, or continued-publication promise" in policy
    assert "Promotion is fail-closed on every track" in policy
