#!/usr/bin/env python3
"""The Matrix Status PR check must ignore results and still catch hand-edits.

`matrix-status.yml` runs on pull_request to catch a hand-edit inside
docs/MATRIX-STATUS.md's generated block. It used to do that by regenerating the
document and requiring the committed copy to match byte for byte, which is not
a property any commit can have: the block is built from build-config.yml AND
from the last RUN_DEPTH runs of two workflows, and the second input moves on
its own. Runs 31089215592 and 31089333089 are two minutes apart on the same
tree and produced "7 of 53" and "8 of 53" — a single-cell LUKS rerun lands its
own result and pushes the oldest full sweep out of the window at the same time.

So the check compares `--shape` output instead. These tests pin both halves of
that bargain: churn in the results must not register, and an edit to the
generator-written prose must.
"""

import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "gen-matrix-status.py"
DOC = REPO_ROOT / "docs" / "MATRIX-STATUS.md"


def _module():
    """Import the script by path — its name has a dash, so no plain import."""
    spec = importlib.util.spec_from_file_location("gen_matrix_status", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


gms = _module()


def _doc(block: str) -> str:
    """A document with hand-written narrative either side of the block."""
    return (
        "# Matrix status\n\nHand-written narrative above.\n\n"
        f"{gms.BEGIN}\n{block}\n{gms.END}\n\nHand-written narrative below.\n"
    )


# Two regenerations of the same tree, minutes apart. Everything that differs
# here differs because CI ran, not because anyone committed anything.
BLOCK_BEFORE = """
*Generated by `scripts/gen-matrix-status.py` — do not edit this block by hand.*

## LUKS E2E

**3 of 54** cells green (41 tested, 13 never tested).

Measured against the set `luks-e2e.yml` schedules.

| Variant | gnome | kde | cosmic | niri | xfce |
|---|:--:|:--:|:--:|:--:|:--:|
| **albacore** | ❌ | ❌ | ❌ | ❌ | ❌ |
| **flounder** | ❌ | ❌ | ❌ | — | ❌ |

NVIDIA cells are **out of scope** for this workflow — 25 stale result(s) remain.

Newest result 2026-08-05, oldest still-authoritative result 2026-08-05.

## Live overlay

**41** tags published.

Missing for 6 ISO cell(s): `gurnard-pantheon`, `hummingbird-base`

## Provenance

| Date | Run | Cells |
|---|---|---|
| 2026-08-05 | [31013418173](https://github.com/tuna-os/tunaOS/actions/runs/31013418173) | 1 |
| 2026-08-05 | [31010736963](https://github.com/tuna-os/tunaOS/actions/runs/31010736963) | 18 |
"""

BLOCK_AFTER = """
*Generated by `scripts/gen-matrix-status.py` — do not edit this block by hand.*

## LUKS E2E

**8 of 53** cells green (11 tested, 42 never tested).

Measured against the set `luks-e2e.yml` schedules.

| Variant | gnome | kde | cosmic | niri | xfce |
|---|:--:|:--:|:--:|:--:|:--:|
| **albacore** | ✅ | ⬜ | ⬜ | ⬜ | ⬜ |
| **flounder** | ✅ | ⬜ | ❌ | — | ✅ |
| **yellowfin** | ⬜ | ⬜ | ✅ | ✅ | ⬜ |

Newest result 2026-08-06, oldest still-authoritative result 2026-08-06.

## Live overlay

**42** tags published.

Every non-NVIDIA ISO cell has an overlay.

## Provenance

| Date | Run | Cells |
|---|---|---|
| 2026-08-06 | [31089226102](https://github.com/tuna-os/tunaOS/actions/runs/31089226102) | 1 |
"""


# ── Churn must not register ─────────────────────────────────────────────────

def test_result_churn_has_the_same_shape():
    """Cells flipping, tallies moving, rows appearing, the window scrolling.

    Including the two conditional paragraphs, which flip with no commit:
    the NVIDIA out-of-scope note is printed only while stale pre-exclusion
    results remain, and the overlay line is an if/else over published tags.
    """
    assert gms.shape(_doc(BLOCK_BEFORE)) == gms.shape(_doc(BLOCK_AFTER))


def test_shape_keeps_the_generator_written_lines():
    """A vacuous shape would pass everything. Assert it kept the skeleton."""
    out = gms.shape(_doc(BLOCK_AFTER))
    assert "## LUKS E2E" in out
    assert "## Live overlay" in out
    assert "## Provenance" in out
    assert "Measured against the set `luks-e2e.yml` schedules." in out
    assert "| Variant | gnome | kde | cosmic | niri | xfce |" in out
    assert "do not edit this block by hand" in out
    # ...and dropped the result-derived lines, or the test above would pass for
    # the wrong reason.
    assert "albacore" not in out
    assert "Newest result" not in out
    assert "31089226102" not in out


def test_digits_in_names_survive_masking():
    """Tallies are masked; `E2E` is not, so a heading edit still shows."""
    out = gms.shape(_doc(BLOCK_AFTER))
    assert "## LUKS E2E" in out
    assert "**N of N** cells green (N tested, N never tested)." in out


# ── Hand-edits must register ────────────────────────────────────────────────

@pytest.mark.parametrize("edit,description", [
    (lambda b: b.replace(
        "Measured against the set `luks-e2e.yml` schedules.",
        "Measured against the ISO matrix."), "prose reworded"),
    (lambda b: b.replace("## Live overlay\n", ""),
     "a section heading deleted"),
    (lambda b: b.replace(
        "| Variant | gnome | kde | cosmic | niri | xfce |",
        "| Variant | gnome | kde | cosmic | niri |"), "a column dropped"),
    (lambda b: b.replace("do not edit this block by hand.", "edit freely."),
     "the do-not-edit notice softened"),
])
def test_hand_edit_changes_the_shape(edit, description):
    edited = gms.shape(_doc(edit(BLOCK_AFTER)))
    assert gms.shape(_doc(BLOCK_AFTER)) != edited, \
        f"{description} slipped through the shape check"


# ── Markers ─────────────────────────────────────────────────────────────────

def test_missing_markers_raise():
    with pytest.raises(ValueError):
        gms.shape("# Matrix status\n\nNo generated block here.\n")


def test_the_real_document_has_a_shape():
    """Guards the marker strings themselves: a rename here fails loudly."""
    out = gms.shape(DOC.read_text())
    assert "## LUKS E2E" in out
    assert "| Variant | gnome | kde | cosmic | niri | xfce |" in out
