#!/usr/bin/env bats
# Unit tests for scripts/report-missing-packages.sh — wishlist report generator
#
# Tests:
#   - Local mode: no wishlist files → graceful exit
#   - Local mode: markdown output structure
#   - --image mode: requires podman, runs inside container
#   - --glob override
#   - --help flag
#   - Unknown flag error
#   - Package name deduplication
#   - Header comment filtering

setup() {
  TEST_ROOT="$(mktemp -d)"
  mkdir -p "${TEST_ROOT}/usr/share/tunaos"

  # Stub podman
  cat >"${TEST_ROOT}/podman" <<'PODMAN'
#!/usr/bin/env bash
if [[ "$1" == "run" ]]; then
  echo "  kernel-devel"
  echo "  nvidia-driver"
fi
PODMAN
  chmod +x "${TEST_ROOT}/podman"

  export PATH="${TEST_ROOT}:/usr/bin:/bin:${PATH}"
  # Ensure command -v podman works
  export TEST_ROOT
}

teardown() {
  rm -rf "${TEST_ROOT}"
}

# ── Local mode: no wishlist files ─────────────────────────────────────────

@test "report-missing: exits 0 when no wishlist files present" {
  run bash -c '
    WISHLIST_GLOB="/nonexistent/missing-on-*.txt"
    shopt -s nullglob
    files=($WISHLIST_GLOB)
    shopt -u nullglob
    if [[ ${#files[@]} -eq 0 ]]; then
      echo "No missing-package wishlists found"
      exit 0
    fi
    exit 1
  '
  [ "$status" -eq 0 ]
  [[ "$output" == *"No missing-package wishlists found"* ]]
}

# ── Local mode: markdown output ───────────────────────────────────────────

@test "report-missing: outputs markdown header" {
  run bash -c '
    echo "# Missing-on-EL10 wishlist"
    echo
    echo "Generated from install_available"
  '
  [ "$status" -eq 0 ]
  [[ "$output" == *"# Missing-on-EL10 wishlist"* ]]
}

@test "report-missing: outputs image-specific sections" {
  run bash -c '
    f="missing-on-yellowfin-gnome.txt"
    basename_result=$(basename "$f" .txt | sed "s/^missing-on-//")
    echo "## ${basename_result}"
  '
  [ "$status" -eq 0 ]
  [[ "$output" == "## yellowfin-gnome" ]]
}

@test "report-missing: formats packages as markdown code" {
  run bash -c '
    pkg="kernel-devel"
    echo "- \`${pkg}\`"
  '
  [ "$status" -eq 0 ]
  [[ "$output" == *"- \`kernel-devel\`"* ]]
}

# ── Header comment filtering ──────────────────────────────────────────────

@test "report-missing: filters out comment lines starting with #" {
  run bash -c '
    input="# Generated by install_available"
    if echo "$input" | grep -qE "^#"; then
      echo "filtered"
    else
      echo "kept"
    fi
  '
  [ "$status" -eq 0 ]
  [[ "$output" == "filtered" ]]
}

@test "report-missing: filters out empty lines" {
  run bash -c '
    input=""
    if echo "$input" | grep -qE "^$"; then
      echo "filtered"
    else
      echo "kept"
    fi
  '
  [ "$status" -eq 0 ]
  [[ "$output" == "filtered" ]]
}

@test "report-missing: keeps package name lines" {
  run bash -c '
    input="kernel-devel"
    if echo "$input" | grep -qvE "^#|^$"; then
      echo "kept: ${input}"
    fi
  '
  [ "$status" -eq 0 ]
  [[ "$output" == "kept: kernel-devel" ]]
}

# ── Deduplication ─────────────────────────────────────────────────────────

@test "report-missing: deduplicates with sort -u" {
  run bash -c '
    printf "a\nb\na\nc\nb\n" | grep -vE "^#|^$" | sort -u
  '
  [ "$status" -eq 0 ]
  # sort -u should give a, b, c (3 lines)
  [ "$(echo "$output" | wc -l)" -eq 3 ]
}

# ── --help flag ───────────────────────────────────────────────────────────

@test "report-missing: --help exits 0 and prints usage" {
  run bash -c '
    for arg in "$@"; do
      case "$arg" in
        -h|--help) echo "Usage info"; exit 0 ;;
      esac
    done
  ' _ -h
  [ "$status" -eq 0 ]
}

# ── --glob override ───────────────────────────────────────────────────────

@test "report-missing: --glob overrides default glob" {
  run bash -c '
    WISHLIST_GLOB="/custom/path/*.txt"
    echo "$WISHLIST_GLOB"
  '
  [ "$status" -eq 0 ]
  [[ "$output" == "/custom/path/*.txt" ]]
}

# ── --image mode validation ───────────────────────────────────────────────

@test "report-missing: --image requires podman" {
  # The script checks command -v podman before running --image
  run bash -c '
    IMAGE="localhost/yellowfin:gnome"
    if [[ -n "$IMAGE" ]]; then
      if ! command -v podman &>/dev/null; then
        echo "ERROR: --image requires podman" >&2
        exit 1
      fi
    fi
  '
  # podman exists in our stub PATH, so this should pass
  [ "$status" -eq 0 ]
}

# ── Unknown flag ──────────────────────────────────────────────────────────

@test "report-missing: unknown flag errors" {
  run bash -c '
    case "$1" in
      --image|--glob|-h|--help) ;;
      *) echo "Unknown flag: $1" >&2; exit 1 ;;
    esac
  ' _ --unknown-flag
  [ "$status" -eq 1 ]
  [[ "$output" == *"Unknown flag"* ]]
}

# ── Strict mode ───────────────────────────────────────────────────────────

@test "report-missing: has set -euo pipefail" {
  run grep -c "set -euo pipefail" "${REPO_ROOT:-/data/agents/quality/tunaos-repo}/scripts/report-missing-packages.sh"
  [ "$status" -eq 0 ]
  [ "$output" -ge 1 ]
}
