#!/usr/bin/env bats
# The install_available wishlist is loud but toothless: every miss is a
# ::warning and a line in /usr/share/tunaos/missing-on-<image>.txt, and no
# warning ever failed a build — so adding a name to any best-effort install
# list silently made that package optional everywhere, forever.
# checks/verify-package-wishlist.sh turns the same file into a fatal gate:
# a miss must be declared in checks/package-miss-allowlist.txt or the build
# goes red. These tests run the real script against fixture wishlists.

REPO_ROOT="${REPO_ROOT:-$(cd "${BATS_TEST_DIRNAME}/../.." && pwd)}"
GATE="${REPO_ROOT}/build_scripts/checks/verify-package-wishlist.sh"
LIB="${REPO_ROOT}/build_scripts/lib.sh"
CLEANUP="${REPO_ROOT}/build_scripts/99-cleanup.sh"
ALLOWLIST_COMMITTED="${REPO_ROOT}/build_scripts/checks/package-miss-allowlist.txt"

setup() {
  WISH_DIR="${BATS_TEST_TMPDIR}/wish"
  mkdir -p "$WISH_DIR"
  ALLOW="${BATS_TEST_TMPDIR}/allow.txt"
  printf 'btop\ncatfish\n' >"$ALLOW"
  export TUNAOS_WISHLIST_DIR="$WISH_DIR"
  export TUNAOS_WISHLIST_ALLOWLIST="$ALLOW"
  unset IS_HUMMINGBIRD || true
}

# Wishlists as record_package_wishlist really writes them: comment header,
# then bare names.
write_wishlist() {
  local image="$1"
  shift
  {
    printf '# Generated by build_scripts/lib.sh:record_package_wishlist\n'
    printf '# image=%s major_version=10 caller=test timestamp=2026-08-07T00:00:00Z\n' "$image"
    printf '%s\n' "$@"
  } >>"${WISH_DIR}/missing-on-${image}.txt"
}

@test "wishlist gate: no wishlist at all passes" {
  run "$GATE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"TUNAOS_WISHLIST_OK"* ]]
}

@test "wishlist gate: allowlisted misses pass and are named" {
  write_wishlist yellowfin btop catfish
  run "$GATE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"TUNAOS_WISHLIST_OK"* ]]
  [[ "$output" == *"btop"* ]]
  [[ "$output" == *"catfish"* ]]
}

@test "wishlist gate: a miss outside the allowlist fails and names the package" {
  write_wishlist yellowfin btop gtkgreeet-typo
  run "$GATE"
  [ "$status" -eq 1 ]
  [[ "$output" == *"TUNAOS_WISHLIST_FAIL"* ]]
  [[ "$output" == *"gtkgreeet-typo"* ]]
  # the allowlisted miss must not be blamed
  [[ "$output" != *"misses=2"* ]]
}

@test "wishlist gate: header comments and blank lines are not package names" {
  # A file that is ONLY the generated header must read as zero misses.
  printf '# Generated by build_scripts/lib.sh:record_package_wishlist\n# image=x caller=y\n\n' \
    >"${WISH_DIR}/missing-on-empty.txt"
  run "$GATE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"TUNAOS_WISHLIST_OK"* ]]
}

@test "wishlist gate: the same miss from two callers is judged once" {
  write_wishlist yellowfin not-allowed
  write_wishlist yellowfin not-allowed
  write_wishlist albacore not-allowed
  run "$GATE"
  [ "$status" -eq 1 ]
  [[ "$output" == *"misses=1"* ]]
}

@test "wishlist gate: hummingbird bootstrap skips with a marker" {
  write_wishlist hummingbird totally-unpackaged-yet
  IS_HUMMINGBIRD=true run "$GATE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"TUNAOS_WISHLIST_SKIPPED"* ]]
}

@test "wishlist gate: missing allowlist with misses present is a loud failure, not a pass" {
  write_wishlist yellowfin btop
  TUNAOS_WISHLIST_ALLOWLIST="${BATS_TEST_TMPDIR}/nope.txt" run "$GATE"
  [ "$status" -eq 1 ]
  [[ "$output" == *"allowlist-not-found"* ]]
}

@test "committed allowlist parses: every non-comment line is one bare package name" {
  [ -f "$ALLOWLIST_COMMITTED" ]
  run grep -Ev '^\s*(#|$)' "$ALLOWLIST_COMMITTED"
  [ "$status" -eq 0 ]  # seeded non-empty
  while IFS= read -r line; do
    [[ "$line" =~ ^[A-Za-z0-9._+-]+$ ]] || {
      echo "not a bare package name: '$line'" >&2
      return 1
    }
  done <<<"$output"
}

# ── wiring pins: the gate has to actually RUN, from the one script every
# family executes last, and both installer families have to feed it ──

@test "99-cleanup.sh invokes the wishlist gate" {
  run bash -c "grep -v '^\s*#' '$CLEANUP' | grep -F 'checks/verify-package-wishlist.sh'"
  [ "$status" -eq 0 ]
}

@test "apt_install_available records its skips to the shared wishlist" {
  # Without this call the gate covers dnf images only — and the measured
  # fastfetch/glow/gum variance lives on the apt side.
  run bash -c "awk '/^apt_install_available\(\)/,/^}/' '$LIB' | grep -v '^\s*#' | grep -F 'record_package_wishlist'"
  [ "$status" -eq 0 ]
}

@test "install_available records its skips via the shared recorder" {
  run bash -c "awk '/^install_available\(\)/,/^}/' '$LIB' | grep -v '^\s*#' | grep -F 'record_package_wishlist'"
  [ "$status" -eq 0 ]
}

@test "record_package_wishlist writes names under TUNAOS_WISHLIST_DIR" {
  # Extract the real function and run it — behavior, not just presence.
  local fn
  fn="$(awk '/^record_package_wishlist\(\)/,/^}/' "$LIB")"
  [[ "$fn" == *'TUNAOS_WISHLIST_DIR'* ]]
  run bash -c "
    ${fn}
    IMAGE_NAME=testimg TUNAOS_WISHLIST_DIR='${WISH_DIR}' \
      record_package_wishlist my-caller.sh pkg-a pkg-b
    cat '${WISH_DIR}/missing-on-testimg.txt'
  "
  [ "$status" -eq 0 ]
  [[ "$output" == *"pkg-a"* ]]
  [[ "$output" == *"pkg-b"* ]]
  [[ "$output" == *"my-caller.sh"* ]]
}
