"""Failure injection: one requested package missing (unallowlisted omission).

Incident: tunaOS#858 (marlin:kde built, promoted, and shipped with no plasma session).
Where to assert: `build_scripts/checks/verify-package-wishlist.sh` + `install_available` / `lib.sh`.

Asserts all five invariant properties:
  (1) Fails: verify-package-wishlist.sh exits non-zero (exit code 1).
  (2) Says why: output outputs TUNAOS_WISHLIST_FAIL and names the unallowlisted missing package.
  (3) Does not call the cell green: no_silent_omissions criterion fails, cell is not composite green.
  (4) Does not promote: wishlist gate failure halts build before image promotion.
  (5) Keeps enough evidence to diagnose: wishlist file records missing packages, caller, and timestamp.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from tests.injection.helpers import (
    ROOT,
    evaluate_composite_status,
    evaluate_promote_condition,
)

VERIFY_SCRIPT = ROOT / "build_scripts" / "checks" / "verify-package-wishlist.sh"


def _run_verify_wishlist(tmp_path: Path, missing_pkgs: list[str], allowlisted_pkgs: list[str]):
    """Run verify-package-wishlist.sh against injected wishlist and allowlist."""
    wish_dir = tmp_path / "wishlist"
    wish_dir.mkdir(parents=True, exist_ok=True)

    wish_file = wish_dir / "missing-on-marlin.txt"
    wish_content = [
        "# Generated by build_scripts/lib.sh:record_package_wishlist",
        "# image=marlin major_version=rolling caller=install-desktop.sh timestamp=2026-09-02T12:00:00Z",
    ] + missing_pkgs
    wish_file.write_text("\n".join(wish_content) + "\n", encoding="utf-8")

    allowlist_file = tmp_path / "package-miss-allowlist.txt"
    allowlist_file.write_text(
        "\n".join(["# Allowlisted packages"] + allowlisted_pkgs) + "\n", encoding="utf-8"
    )

    env = dict(os.environ)
    env["TUNAOS_WISHLIST_DIR"] = str(wish_dir)
    env["TUNAOS_WISHLIST_ALLOWLIST"] = str(allowlist_file)
    env["IS_HUMMINGBIRD"] = "false"

    return subprocess.run(
        ["bash", str(VERIFY_SCRIPT)],
        capture_output=True,
        text=True,
        env=env,
        cwd=ROOT,
    )


def test_property_1_and_2_unallowlisted_missing_package_fails_and_says_why(tmp_path):
    """(1) Fails and (2) says why: gate exits 1 and explicitly names unallowlisted missing package."""
    missing = ["plasma-workspace-wayland"]  # The #858 critical package!
    allowlist = ["optional-font-package"]

    proc = _run_verify_wishlist(tmp_path, missing, allowlist)

    # (1) Fails
    assert proc.returncode == 1, "verify-package-wishlist.sh must fail on unallowlisted missing package"

    # (2) Says why
    assert "TUNAOS_WISHLIST_FAIL misses=1" in proc.stderr
    assert "plasma-workspace-wayland" in proc.stderr
    assert "NOT in checks/package-miss-allowlist.txt" in proc.stderr


def test_allowlisted_package_miss_passes_honestly(tmp_path):
    """Allowed misses pass with confirmation in stdout."""
    missing = ["optional-font-package"]
    allowlist = ["optional-font-package"]

    proc = _run_verify_wishlist(tmp_path, missing, allowlist)
    assert proc.returncode == 0
    assert "TUNAOS_WISHLIST_OK misses=1 (all allowlisted)" in proc.stdout
    assert "optional-font-package" in proc.stdout


def test_property_3_missing_package_does_not_call_cell_green():
    """(3) Does not call the cell green: omissions failure marks cell not green."""
    stage = {
        "marlin": {
            "jobs": {
                ("kde", "Promote"): "success",
                ("kde", "Gate"): "success",
            },
            "date": "2026-09-02",
        }
    }
    # no_silent_omissions is a blocking criterion; when it fails:
    omissions = {"marlin:kde": ("failure", "2026-09-02", "32000000000")}
    green, total, lines, prov = evaluate_composite_status(stage, omissions=omissions)
    assert green == 0, "Cell failing no_silent_omissions must not be composite green"
    verdict = prov.get("marlin:kde", {}).get("no_silent_omissions", {}).get("verdict")
    assert verdict == "fail"


def test_property_4_missing_package_does_not_promote():
    """(4) Does not promote: verify-package-wishlist failure in build stops promotion."""
    needs_results = {
        "build_push": "failure",
        "manifest": "skipped",
        "sign": "skipped",
        "verify_boot": "skipped",
    }
    assert evaluate_promote_condition(needs_results) is False, "Promote must not execute when wishlist gate fails"


def test_property_5_missing_package_keeps_diagnostic_evidence(tmp_path):
    """(5) Keeps enough evidence to diagnose: wishlist file records metadata and packages."""
    missing = ["plasma-workspace-wayland", "plasma-desktop"]
    allowlist = []

    proc = _run_verify_wishlist(tmp_path, missing, allowlist)

    # Wishlist file preserved on disk
    wish_file = tmp_path / "wishlist" / "missing-on-marlin.txt"
    assert wish_file.exists()
    content = wish_file.read_text()
    assert "caller=install-desktop.sh" in content
    assert "image=marlin" in content
    assert "plasma-workspace-wayland" in content
    assert "plasma-desktop" in content
