#!/usr/bin/env python3
"""Render each variant's lettermark: its emoji, its name, its accent.

    scripts/branding/make-lettermarks.py

The variant is the brand: GDM, the Plasma splash and the installer show
"Marlin" or "Sailfin", never "TunaOS". Each lettermark is the variant's Noto
Emoji, its name set in Baloo 2 ExtraBold (SIL Open Font License), and an
underline in the accent borrowed from its base distro
(build_scripts/lib/variant-identity.tsv).

The text is converted to outlines, so the SVGs need no font at runtime.
Writes, per variant:

    system_files/usr/share/tunaos/lettermarks/<variant>.svg        light text, for dark screens
    system_files/usr/share/tunaos/lettermarks/<variant>-dark.svg   dark text, for light screens

Needs fontTools and uharfbuzz; fetches Baloo 2 from google/fonts into a cache.
The output is committed; builds never run this.
"""

import io
import re
import urllib.request
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

REPO = Path(__file__).resolve().parents[2]
TSV = REPO / "build_scripts/lib/variant-identity.tsv"
LOGOS = REPO / "system_files/usr/share/tunaos/logos"
OUT = REPO / "system_files/usr/share/tunaos/lettermarks"
FONT_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/baloo2/Baloo2%5Bwght%5D.ttf"
CACHE = Path.home() / ".cache/tunaos-branding/Baloo2.ttf"
WEIGHT = 800
SIZE = 100  # font size in SVG units
LIGHT, DARK = "#F4F7FB", "#0D1B2A"

# The name os-release shows: bonito-rawhide publishes as bonito, and
# flounder-sid as flounder. Their colour and emoji tell them apart.
DISPLAY = {"bonito-rawhide": "Bonito", "flounder-sid": "Flounder"}


def font_bytes():
    if not CACHE.exists():
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(FONT_URL, timeout=60) as r:
            CACHE.write_bytes(r.read())
    tt = TTFont(str(CACHE))
    inst = instantiateVariableFont(tt, {"wght": WEIGHT})
    buf = io.BytesIO()
    inst.save(buf)
    return buf.getvalue()


def text_path(data, text):
    """Return (svg path d, advance width, ascender, descender) at SIZE."""
    tt = TTFont(io.BytesIO(data))
    upem = tt["head"].unitsPerEm
    scale = SIZE / upem
    face = hb.Face(data)
    f = hb.Font(face)
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(f, buf, {"kern": True, "liga": True})
    glyphs = tt.getGlyphSet()
    order = tt.getGlyphOrder()
    pen = SVGPathPen(glyphs)
    x = 0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = order[info.codepoint]
        # Flip y (fonts are y-up, SVG is y-down) and place on the baseline.
        tp = TransformPen(pen, (scale, 0, 0, -scale, (x + pos.x_offset) * scale, -pos.y_offset * scale))
        glyphs[name].draw(tp)
        x += pos.x_advance
    os2 = tt["OS/2"]
    return pen.getCommands(), x * scale, os2.sCapHeight * scale


def emoji_body(vid):
    raw = (LOGOS / f"{vid}.svg").read_text()
    raw = re.sub(r"<\?xml[^>]*>|<!--[\s\S]*?-->", "", raw)
    vb = re.search(r'viewBox="([^"]+)"', raw).group(1)
    body = re.sub(r"^[\s\S]*?<svg\b[^>]*>", "", raw, count=1)
    body = re.sub(r"</svg>\s*$", "", body)
    p = f"{vid}-"
    body = re.sub(r'\bid="([^"]+)"', lambda m: f'id="{p}{m.group(1)}"', body)
    body = re.sub(r"url\(#([^)]+)\)", lambda m: f"url(#{p}{m.group(1)})", body)
    body = re.sub(r'href="#([^"]+)"', lambda m: f'href="#{p}{m.group(1)}"', body)
    return vb, body


def lettermark(data, vid, accent, colour):
    name = DISPLAY.get(vid, vid.capitalize())
    d, advance, cap = text_path(data, name)
    vb, body = emoji_body(vid)
    mark = cap * 1.55  # the emoji stands a little taller than the capitals
    gap = SIZE * 0.18
    pad = SIZE * 0.08
    bar_h = SIZE * 0.09
    text_x = pad + mark + gap
    baseline = pad + mark * 0.5 + cap * 0.5
    bar_y = baseline + SIZE * 0.2
    width = text_x + advance + pad
    height = max(pad + mark + pad, bar_y + bar_h + pad)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- {name}: generated by scripts/branding/make-lettermarks.py. Type: Baloo 2 (SIL OFL 1.1); mark: Noto Emoji (Apache 2.0). -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 {width:.1f} {height:.1f}" width="{width:.0f}" height="{height:.0f}">
  <title>{name}</title>
  <svg x="{pad:.1f}" y="{pad:.1f}" width="{mark:.1f}" height="{mark:.1f}" viewBox="{vb}">{body}</svg>
  <path transform="translate({text_x:.1f} {baseline:.1f})" fill="{colour}" d="{d}"/>
  <rect x="{text_x:.1f}" y="{bar_y:.1f}" width="{advance * 0.62:.1f}" height="{bar_h:.1f}" rx="{bar_h / 2:.1f}" fill="{accent}"/>
</svg>
"""


def main():
    data = font_bytes()
    OUT.mkdir(parents=True, exist_ok=True)
    for row in TSV.read_text().splitlines():
        if not row or row.startswith("#"):
            continue
        vid, accent = row.split("\t")[:2]
        (OUT / f"{vid}.svg").write_text(lettermark(data, vid, accent, LIGHT))
        (OUT / f"{vid}-dark.svg").write_text(lettermark(data, vid, accent, DARK))
        print(f"{vid}")


if __name__ == "__main__":
    main()
