id: bonito
emoji: "🎣"
description: "Based on Fedora 44"
base_image: "quay.io/fedora/fedora-bootc:44"
akmods: "ublue-os"
platforms: ["linux/amd64", "linux/arm64"]
flavors:
  - id: base
    stage: 1
    build_image: true
    build_iso: false
    build_qcow2: false
  - id: base-hwe
    stage: 2
    build_image: true
    build_iso: false
    build_qcow2: false
  - id: base-nvidia
    stage: 2
    build_image: true
    build_iso: false
    build_qcow2: false
  - id: gnome
    stage: 2
    build_image: true
    build_iso: true
    build_qcow2: true
  - id: cosmic
    stage: 2
    build_image: true
    build_iso: true
    build_qcow2: false
  - id: kde
    stage: 2
    build_image: true
    build_iso: true
    build_qcow2: false
  - id: niri
    stage: 2
    build_image: true
    build_iso: true
    build_qcow2: false
  - id: gnome-hwe
    stage: 3
    build_image: true
    build_iso: false
    build_qcow2: false
  - id: gnome-nvidia
    stage: 3
    build_image: true
    build_iso: true
    build_qcow2: false
  - id: cosmic-nvidia
    stage: 3
    build_image: true
    build_iso: true
    build_qcow2: false
  - id: kde-nvidia
    stage: 3
    build_image: true
    build_iso: true
    build_qcow2: false
  - id: niri-nvidia
    stage: 3
    build_image: true
    build_iso: true
    build_qcow2: false
