#!/usr/bin/env bash
# scripts/gen-screenshot-gallery.sh — regenerate docs/SCREENSHOTS.md from
# whatever captures exist under docs/images/. One page, every screenshot the
# pipeline produces (desktops, installer flows, e2e boot evidence), so visual
# verification is a single scroll instead of an artifact scavenger hunt.
#
# Run by the commit-to-repo jobs in weekly-desktop-screenshots.yml and
# installer-screenshots.yml; safe to run locally any time.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
OUT="docs/SCREENSHOTS.md"

{
	echo "# TunaOS Screenshot Gallery"
	echo
	echo "> Auto-generated by \`scripts/gen-screenshot-gallery.sh\` from"
	echo "> \`docs/images/\` — regenerated whenever the screenshot workflows"
	echo "> commit fresh captures. Edit the script, not this file."
	echo

	if compgen -G "docs/images/desktops/*.png" >/dev/null; then
		echo "## Desktops (live-session captures, weekly)"
		echo
		echo "| Variant:Flavor | Capture |"
		echo "|---|---|"
		for png in docs/images/desktops/*.png; do
			base="$(basename "$png" .png)"
			echo "| \`${base}\` | ![${base}](images/desktops/${base}.png) |"
		done
		echo
	fi

	if compgen -G "docs/images/installer/*.png" >/dev/null; then
		echo "## Installer flows (walkthrough captures, weekly)"
		echo
		# Group by prefix: files like 01_welcome.png (default flow) and
		# cosmic_01_welcome.png (cosmic flow) render as one row per flow.
		flows=$(for f in docs/images/installer/*.png; do
			b=$(basename "$f" .png)
			case "$b" in
			[0-9]*) echo "default" ;;
			*) echo "${b%%_[0-9]*}" ;;
			esac
		done | sort -u)
		for flow in $flows; do
			echo "### ${flow} flow"
			echo
			for png in docs/images/installer/*.png; do
				b=$(basename "$png" .png)
				case "$flow:$b" in
				default:[0-9]*) ;;
				"$flow:${flow}_"*) ;;
				*) continue ;;
				esac
				echo "**${b}**"
				echo
				echo "![${b}](images/installer/${b}.png)"
				echo
			done
		done
	fi

	if compgen -G "docs/images/e2e/*/*.png" >/dev/null; then
		echo "## E2E boot evidence (per variant:flavor)"
		echo
		for dir in docs/images/e2e/*/; do
			cell="$(basename "$dir")"
			echo "### ${cell}"
			echo
			for png in "$dir"*.png; do
				b=$(basename "$png" .png)
				echo "**${b}**"
				echo
				echo "![${cell}/${b}](images/e2e/${cell}/${b}.png)"
				echo
			done
		done
	fi

	echo "---"
	echo "_Last regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
} >"$OUT"

echo "wrote $OUT"
