---
name: Build ISOs

on:
  workflow_dispatch:
    inputs:
      upload-to-cloudflare:
        description: "Upload to Cloudflare"
        required: false
        default: false
        type: boolean
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-iso.yml'
      - 'iso_files/*'
      - 'Justfile'

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "${{ github.ref_name }}"
  DEFAULT_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISOs
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-24.04' || 'linux/amd64/v2' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64,linux/amd64/v2,linux/arm64]
        flavor: ["dx", ""]
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Install dependencies
        if: matrix.platform == 'linux/arm64'
        run: |
          set -x
          sudo apt update -y
          sudo apt install -y \
            podman

      - name: Mount BTRFS for podman storage
        if: ${{ matrix.platform != 'linux/arm64' && inputs.cleanup_runner }}
        uses: ublue-os/container-storage-action@main

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Format image ref
        id: image_ref
        env:
          FLAVOR: ${{ matrix.flavor }}
        run: |
          OUTPUT_NAME="${IMAGE_REGISTRY}/${IMAGE_NAME}"
          if [ "$FLAVOR" != "" ] ; then
            OUTPUT_NAME="${OUTPUT_NAME}-${FLAVOR}"
          fi
          echo "image_ref=$OUTPUT_NAME" >> "${GITHUB_OUTPUT}"
          

      - name: Build ISO
        id: build
        uses: ublue-os/titanoboa@anaconda-webui-format
        with:
          image-ref: ${{ steps.image_ref.outputs.image_ref }}:${{ env.DEFAULT_TAG }}
          flatpaks-list: ${{ github.workspace }}/system_files/etc/ublue-os/system-flatpaks.list
          hook-post-rootfs: ${{ github.workspace }}/iso_files/configure_iso.sh

      - name: Rename ISO
        id: rename
        env:
          OUTPUT_PATH: ${{ steps.build.outputs.iso-dest }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          PLATFORM: ${{ matrix.platform }}
          DEFAULT_TAG: ${{ env.DEFAULT_TAG }}
          FLAVOR: ${{ matrix.flavor }}
        run: |
          set -x
          mkdir -p output
          OUTPUT_DIRECTORY="$(realpath output)"
          if [ "${FLAVOR}" != "" ] ; then
            IMAGE_NAME="${IMAGE_NAME}-${FLAVOR}"
          fi
          if [ $PLATFORM == "linux/amd64" ]; then
            sha256sum "${OUTPUT_PATH}" | tee "${OUTPUT_DIRECTORY}/${IMAGE_NAME}-${DEFAULT_TAG}.iso-CHECKSUM"
            mv "${OUTPUT_PATH}" "${OUTPUT_DIRECTORY}/${IMAGE_NAME}-${DEFAULT_TAG}-x86_64.iso"
          if [ $PLATFORM == "linux/amd64/v2" ]; then
            sha256sum "${OUTPUT_PATH}" | tee "${OUTPUT_DIRECTORY}/${IMAGE_NAME}-${DEFAULT_TAG}.iso-CHECKSUM"
            mv "${OUTPUT_PATH}" "${OUTPUT_DIRECTORY}/${IMAGE_NAME}-${DEFAULT_TAG}-x86_64_v2.iso"
          if [ $PLATFORM == "linux/arm64" ]; then
            sha256sum "${OUTPUT_PATH}" | tee "${OUTPUT_DIRECTORY}/${IMAGE_NAME}-${DEFAULT_TAG}.iso-CHECKSUM"
            mv "${OUTPUT_PATH}" "${OUTPUT_DIRECTORY}/${IMAGE_NAME}-${DEFAULT_TAG}-arm64.iso"
          
          fi
          echo "output_directory=$OUTPUT_DIRECTORY" >> "${GITHUB_OUTPUT}"

      - name: Upload to Job Artifacts
        if: inputs.upload-to-cloudflare == false
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.DEFAULT_TAG }}-${{ matrix.platform }}-iso
          if-no-files-found: error
          path: ${{ steps.rename.outputs.output_directory }}

      - name: Upload to CloudFlare
        if: inputs.upload-to-cloudflare == true && github.event_name != 'pull_request'
        shell: bash
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_REGION: auto
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          SOURCE_DIR: ${{ steps.rename.outputs.output_directory }}
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone copy "${SOURCE_DIR}" R2:tunaos