name: Build Bluefin LTS GDX

on:
  pull_request:
    branches:
      - main
      - F42
      - a10
      - a10s
  push:
    branches:
      - main
      - F42
      - a10
      - a10s
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: bluefin-gdx
      flavor: gdx
      default-tag: ${{ github.ref_name == 'main' && 'lts' || github.ref_name }}
      rechunk: ${{ github.event_name != 'pull_request' }}
      sbom: ${{ github.event_name != 'pull_request' }}
      publish: ${{ github.event_name != 'pull_request' }}
