name: Build Guppy [experimental]
on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor (all, base, gnome, kde, niri, etc.)'
        default: 'all'
        type: string

concurrency:
  group: build-guppy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🌈-guppy
    uses: ./.github/workflows/build-variant.yml
    with:
      variant: 'guppy'
      flavor: ${{ inputs.flavor || 'all' }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
