---
name: Sync README Across Branches

'on':
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch to sync README from'
        required: false
        default: 'main'
      target_branches:
        description: 'Target branches (comma-separated)'
        required: false
        default: 'albacore,albacore-server,yellowfin,bluefin-tuna'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    if: github.repository == 'hanthor/tunaOS'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email \
            "github-actions[bot]@users.noreply.github.com"

      - name: Sync README to production branches
        run: |
          SOURCE_BRANCH="${{ github.event.inputs.source_branch || 'main' }}"
          TARGET_BRANCHES="${{
            github.event.inputs.target_branches ||
            'albacore,albacore-server,yellowfin,bluefin-tuna'
          }}"

          echo "🔄 Starting README sync from $SOURCE_BRANCH"
          echo "📋 Target branches: $TARGET_BRANCHES"

          # Ensure we're on the source branch and get the latest README
          git checkout "$SOURCE_BRANCH"
          git pull origin "$SOURCE_BRANCH"

          # Check if README.md exists
          if [ ! -f "README.md" ]; then
            echo "❌ README.md not found in $SOURCE_BRANCH branch"
            exit 1
          fi

          # Store the README content
          cp README.md /tmp/readme_to_sync.md

          # Convert comma-separated branches to array
          IFS=',' read -ra BRANCHES <<< "$TARGET_BRANCHES"

          for branch in "${BRANCHES[@]}"; do
            branch=$(echo "$branch" | xargs) # trim whitespace
            echo "🌟 Processing branch: $branch"

            # Check if branch exists
            if ! git show-ref --verify --quiet \
              "refs/remotes/origin/$branch"; then
              echo "⚠️  Branch $branch does not exist, skipping"
              continue
            fi

            # Checkout target branch
            git checkout "$branch"
            git pull origin "$branch"

            # Compare README files
            if ! cmp -s README.md /tmp/readme_to_sync.md; then
              echo "📝 README differs in $branch, updating..."
              cp /tmp/readme_to_sync.md README.md

              # Commit and push changes
              git add README.md
              git commit -m "📖 Sync README from $SOURCE_BRANCH branch

              This commit automatically syncs the README.md file from the \
              $SOURCE_BRANCH branch to maintain consistency across all \
              production branches.

              Source: ${{ github.sha }}
              Triggered by: ${{ github.event_name }}
              Actor: ${{ github.actor }}"

              git push origin "$branch"
              echo "✅ README synced to $branch"
            else
              echo "✅ README already up-to-date in $branch"
            fi
          done

          echo "🎉 README sync completed successfully!"

      - name: Create summary
        run: |
          echo "## 📖 README Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Source Branch:** \
            ${{ github.event.inputs.source_branch || 'main' }}" \
            >> $GITHUB_STEP_SUMMARY
          echo "**Target Branches:** \
            ${{ github.event.inputs.target_branches ||
            'albacore,albacore-server,yellowfin,bluefin-tuna' }}" \
            >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.event_name }}" \
            >> $GITHUB_STEP_SUMMARY
          echo "**Actor:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The README.md file has been successfully synced across \
            all production branches." >> $GITHUB_STEP_SUMMARY
